language: node_js
sudo: false
node_js:
- '6'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
script: npm run crossbrowser
env:
  matrix:
  - CXX=g++-4.8
  global:
  - secure: HCMrykhJlLO2TJOYCPuBjiUoG3fYs22W7VvjMEHJrDDupQvGnQXCiDoriwz/V4ssdaUWqykwY885QLuJFbkxSSTpv51Ge5O/sJIMwjCflaoksMvVopEqIA54ykv743O/CkFMeydscuaMVGi63/NojpnXpz9N0p+0ZwJCU3z83Ro=
  - secure: kk5vjO9b6W6CnAU4Kd+9hi614e5qkfUetiQECygQa/dTrWvbAeth0ZwvmuGNFoWACj/WqlE2VRhmDMsNVWD2akdwpVc9TftQFweRFD70Svw9Pfu/91eibZnCMmeVflM8ke/MAyb0lTtwhb9yWL+y+o8LrAhPl+B83TXlAoh0hbs=
